version: '3.0'
services:
  db:
    container_name: db
    image: postgres:11.9-alpine
    volumes:
      - ./.data/db_data/postgres_test:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1111